import { 
  Home, Settings, User, FileText, Folder, SquareUser, VenetianMask,
  Bell, Bookmark, Calendar, Camera, CheckCircle, Clock, Cloud, Code,
  Compass, Copy, CreditCard, Database, Edit, Eye, Filter, Flag, Globe,
  Heart, HelpCircle, Image, Inbox, Key, Layers, Link, List, Lock,
  LogOut, Mail, Map, MessageCircle, Monitor, Music, Package, Phone,
  Play, Printer, Save, Search, Send, Share, Shield, ShoppingCart,
  Star, Sun, Tag, Terminal, Trash, TrendingUp, Upload, Video, Wifi, Wrench
} from "lucide-react";

export const iconList = [
  { name: 'Home', icon: Home },
  { name: 'Setting', icon: Settings },
  { name: "User", icon: User },
  { name: "FileText", icon: FileText },
  { name: "Folder", icon: Folder },
  { name: 'SquareUser', icon: SquareUser },
  { name: 'VenetianMask', icon: VenetianMask },
  { name: "Bell", icon: Bell },
  { name: "Bookmark", icon: Bookmark },
  { name: "Calendar", icon: Calendar },
  { name: "Camera", icon: Camera },
  { name: "CheckCircle", icon: CheckCircle },
  { name: "Clock", icon: Clock },
  { name: "Cloud", icon: Cloud },
  { name: "Code", icon: Code },
  { name: "Compass", icon: Compass },
  { name: "Copy", icon: Copy },
  { name: "CreditCard", icon: CreditCard },
  { name: "Database", icon: Database },
  { name: "Edit", icon: Edit },
  { name: "Eye", icon: Eye },
  { name: "Filter", icon: Filter },
  { name: "Flag", icon: Flag },
  { name: "Globe", icon: Globe },
  { name: "Heart", icon: Heart },
  { name: "HelpCircle", icon: HelpCircle },
  { name: "Image", icon: Image },
  { name: "Inbox", icon: Inbox },
  { name: "Key", icon: Key },
  { name: "Layers", icon: Layers },
  { name: "Link", icon: Link },
  { name: "List", icon: List },
  { name: "Lock", icon: Lock },
  { name: "LogOut", icon: LogOut },
  { name: "Mail", icon: Mail },
  { name: "Map", icon: Map },
  { name: "MessageCircle", icon: MessageCircle },
  { name: "Monitor", icon: Monitor },
  { name: "Music", icon: Music },
  { name: "Package", icon: Package },
  { name: "Phone", icon: Phone },
  { name: "Play", icon: Play },
  { name: "Printer", icon: Printer },
  { name: "Save", icon: Save },
  { name: "Search", icon: Search },
  { name: "Send", icon: Send },
  { name: "Share", icon: Share },
  { name: "Shield", icon: Shield },
  { name: "ShoppingCart", icon: ShoppingCart },
  { name: "Star", icon: Star },
  { name: "Sun", icon: Sun },
  { name: "Tag", icon: Tag },
  { name: "Terminal", icon: Terminal },
  { name: "Trash", icon: Trash },
  { name: "TrendingUp", icon: TrendingUp },
  { name: "Upload", icon: Upload },
  { name: "Video", icon: Video },
  { name: "Wifi", icon: Wifi },
  { name: "Wrench", icon: Wrench }
];
